### ISSUE TITLE
lib/index.js missing in 2.0 release

### ISSUE THREAD

**Issue by codymartin** [EasyGraphQL/easygraphql-load-tester#57]
I receive this error when trying to use v2.0

Error: Cannot find module '<projectfolder>/node_modules/easygraphql-load-tester/lib/index.js'. Please verify that the package.json has a valid "main" entry

easygraphql-load-tester's  package.json has: ""main": "lib/index.js","

lib/index.js is not in the package folder under node_modules

<img width="744" alt="2020-01-28_16-00-51" src="https://user-images.githubusercontent.com/4775990/73315952-29aaac00-41f7-11ea-9f19-93b7939dfcca.png">

**Comment by codymartin** [comment]
I was able to build from source and copy the lib folder over to my project as a work around but others will have the same problem. thanks for creating this project. its helping me out a lot. cheers

**Comment by estrada9166** [comment]
Thanks for creating this issue! 

Would you like to create a PR fixing it?

**Comment by estrada9166** [comment]
I published a new version, it seems to be working fine on it `v2.0.1`
